openapi: 3.0.3
info:
  title: DatabaseBRIDANTB
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/kategoris:
    get:
      summary: ''
      operationId: getApiKategoris
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/kategoris could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/kategoris could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/kategoris/{tipe}':
    get:
      summary: ''
      operationId: getApiKategorisTipe
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/kategoris/corporis could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/kategoris/corporis could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: tipe
        description: ''
        example: corporis
        required: true
        schema:
          type: string
  /api/instansis:
    get:
      summary: ''
      operationId: getApiInstansis
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/instansis could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/instansis could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/instansis/{slug}':
    get:
      summary: ''
      operationId: getApiInstansisSlug
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/instansis/et could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/instansis/et could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: slug
        description: 'The slug of the instansi.'
        example: et
        required: true
        schema:
          type: string
  /api/jenis-programs:
    get:
      summary: ''
      operationId: getApiJenisPrograms
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/jenis-programs could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/jenis-programs could not be found.'
      tags:
        - Endpoints
      security: []
  /api/eduwisatas:
    get:
      summary: ''
      operationId: getApiEduwisatas
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas could not be found.'
      tags:
        - Endpoints
      security: []
  /api/eduwisatas/daerah-eduwisata:
    get:
      summary: ''
      operationId: getApiEduwisatasDaerahEduwisata
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas/daerah-eduwisata could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas/daerah-eduwisata could not be found.'
      tags:
        - Endpoints
      security: []
  /api/eduwisatas/asal-lembaga:
    get:
      summary: ''
      operationId: getApiEduwisatasAsalLembaga
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas/asal-lembaga could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas/asal-lembaga could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/eduwisatas/asal-lembaga/{label}':
    get:
      summary: ''
      operationId: getApiEduwisatasAsalLembagaLabel
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas/asal-lembaga/voluptatem could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas/asal-lembaga/voluptatem could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: label
        description: ''
        example: voluptatem
        required: true
        schema:
          type: string
  /api/eduwisatas/daerah-lembaga:
    get:
      summary: ''
      operationId: getApiEduwisatasDaerahLembaga
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas/daerah-lembaga could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas/daerah-lembaga could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/eduwisatas/daerah-lembaga/{label}':
    get:
      summary: ''
      operationId: getApiEduwisatasDaerahLembagaLabel
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/eduwisatas/daerah-lembaga/omnis could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/eduwisatas/daerah-lembaga/omnis could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: label
        description: ''
        example: omnis
        required: true
        schema:
          type: string
  /api/inovasis:
    get:
      summary: ''
      operationId: getApiInovasis
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/inovasis could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/inovasis could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/inovasis/{slug}':
    get:
      summary: ''
      operationId: getApiInovasisSlug
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/inovasis/mesin-pencabut-uang could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/inovasis/mesin-pencabut-uang could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: slug
        description: 'The slug of the inovasi.'
        example: mesin-pencabut-uang
        required: true
        schema:
          type: string
  /api/daerah-inovasi:
    get:
      summary: ''
      operationId: getApiDaerahInovasi
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/daerah-inovasi could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/daerah-inovasi could not be found.'
      tags:
        - Endpoints
      security: []
  /api/risets:
    get:
      summary: ''
      operationId: getApiRisets
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/risets could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/risets could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/risets/{slug}':
    get:
      summary: ''
      operationId: getApiRisetsSlug
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/risets/voluptas could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/risets/voluptas could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: slug
        description: 'The slug of the riset.'
        example: voluptas
        required: true
        schema:
          type: string
  /api/daerah-riset:
    get:
      summary: ''
      operationId: getApiDaerahRiset
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/daerah-riset could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/daerah-riset could not be found.'
      tags:
        - Endpoints
      security: []
  /api/bukus:
    get:
      summary: ''
      operationId: getApiBukus
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/bukus could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/bukus could not be found.'
      tags:
        - Endpoints
      security: []
  '/api/bukus/{slug}':
    get:
      summary: ''
      operationId: getApiBukusSlug
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route api/bukus/totam could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route api/bukus/totam could not be found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: slug
        description: 'The slug of the buku.'
        example: totam
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
